name: Build and Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # IMPORTANT: Add the deployment token to your repository secrets as
          # AZURE_STATIC_WEB_APPS_API_TOKEN (see instructions below).
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # For PR comments
          action: "upload"
          # app_location is repository root in this repo
          app_location: "/"
          api_location: ""
          # We build into docs/ locally (postbuild script). The workflow runs the build
          # which will produce docs/ via the postbuild script; upload that.
          output_location: "docs"
